In [2]:
import requests
import pandas as pd

In [4]:
DDP_USERNAME = ''
DDP_PASSWORD = ''

In [5]:
dic_satnogs = {
    "artifacts": "https://db.satnogs.org/api/artifacts/",
    "modes": "https://db.satnogs.org/api/modes/",
    "satellites": "https://db.satnogs.org/api/satellites/",
    "transmitters": "https://db.satnogs.org/api/transmitters/",
    "telemetry": "https://db.satnogs.org/api/telemetry/",
    "tle": "https://db.satnogs.org/api/tle/",
    "optical-observations": "https://db.satnogs.org/api/optical-observations/"
}

https://db.satnogs.org/api/

In [6]:
dic_satnogs['satellites']

'https://db.satnogs.org/api/satellites/'

In [7]:
r = requests.get(dic_satnogs['satellites'])       #, auth=(DDP_USERNAME, DDP_PASSWORD))
try : 
    data = r.json()
    df = pd.DataFrame.from_dict(data)
except : pass

In [8]:
df

,sat_id,norad_cat_id,norad_follow_id,name,names,image,status,decayed,launched,deployed,website,operator,countries,telemetries,updated,citation,is_frequency_violator,associated_satellites
0,SCHX-0895-2361-9925-0309,965.0,NaN,TRANSIT 5B-5,OPS 6582,satellites/transit-o__1.jpg,alive,None,1964-12-13T00:00:00Z,None,,None,US,[],2022-08-01T06:47:53.992153Z,https://github.com/happysat/Deadsat#1,False,[]
1,AMOM-6643-5608-9156-4431,1002.0,NaN,LES-1,Lincoln Experimental Satellite 1,satellites/LES1-Star13A-Kick-Motor.jpg,alive,None,1965-02-11T00:00:00Z,None,,None,US,[],2022-08-01T18:46:19.317207Z,https://github.com/happysat/Deadsat#23,False,[]
2,KEFJ-8497-6394-9368-1937,1291.0,NaN,SOLRAD-7B,,,alive,None,1965-03-09T00:00:00Z,None,,None,US,[],2022-08-01T18:44:58.681317Z,CITATION NEEDED - https://xkcd.com/285/,False,[]
3,FBFQ-2056-7966-4855-0749,1315.0,NaN,SECOR 4,EGRS 4,,alive,None,1965-04-03T00:00:00Z,None,https://en.wikipedia.org/wiki/SECOR,None,US,[],2022-08-01T16:44:53.958027Z,CITATION NEEDED - https://xkcd.com/285/,False,[]
4,BIRW-7828-0822-0647-1194,1804.0,NaN,ALOUETTE-2,,,alive,None,1965-11-29T00:00:00Z,None,,None,CA,[],2022-08-01T18:44:19.383815Z,https://github.com/happysat/Deadsat,False,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1822,MRPP-0177-8730-4342-4895,58305.0,NaN,FLOCK 4Q 18,2023-174BB,,alive,None,2023-11-11T00:00:00Z,2023-11-11T00:00:00Z,,None,US,[],2024-04-02T11:52:27.046368Z,https://docs.google.com/document/d/1lc1I_erIm0...,False,[]
1823,BRGA-9299-0428-6736-3326,58825.0,NaN,Object F,2024-016F,,alive,None,2024-01-23T00:00:00Z,2024-01-23T00:00:00Z,,None,CN,[],2024-04-04T13:59:47.078163Z,https://docs.google.com/document/d/1FVBr9d6P8h...,False,[]
1824,KCZB-1791-3572-6915-1430,59130.0,NaN,Ghost 5,20224-043AJ,,alive,None,2024-03-04T00:00:00Z,2024-03-04T00:00:00Z,,None,US,[],2024-04-06T08:50:18.946691Z,https://docs.google.com/document/d/1m_P86yDF2t...,False,[]
1825,CLOQ-0995-4096-9502-6975,40017.0,NaN,TabletSat-Aurora,RS13S,satellites/1280px-SPUTNIX_TabletSat-Aurora.jpeg,alive,None,2014-06-19T00:00:00Z,None,https://sputnix.ru/ru/sputniki/na-orbite/table...,None,RU,[],2024-04-07T17:11:14.942875Z,https://www.n2yo.com/satellite/?s=40017,True,[]
1826,ZETQ-9103-3524-7152-2565,38861.0,NaN,SJ-9B,2012-056B,,alive,None,2012-10-14T00:00:00Z,2012-10-14T00:00:00Z,,None,CN,[],2024-04-07T19:21:43.447399Z,https://db.satnogs.org/satellite/KPZZ-0499-235...,False,[]